version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: mongodb://mongo:27017/student-forum
    depends_on:
      - mongo
    volumes:
      - .:/app
    working_dir: /app/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'  
    depends_on:
      - backend

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"

  test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm test
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/testingDB
